version: '3.5'

services:
  website:
    container_name: website
    build: .
    ports:
      - "8000:3000"
    networks:
      - postgres-network
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules


networks:
  postgres-network:
    driver: bridge
